In [10]:
import numpy as np

# rows = days, columns = rooms
energy = np.array([
    [30, 45, 22, 60, 35],
    [32, 47, 21, 58, 36],
    [31, 50, 25, 65, 38],
    [29, 43, 20, 55, 34],
    [35, 52, 26, 70, 40],
    [40, 60, 30, 80, 45],
    [38, 58, 28, 78, 44]
])

print(energy.shape)   # (7, 5)


(7, 5)


In [11]:
# total usage per room
print(energy.sum(axis=0))

# total usage per day
print(energy.sum(axis=1))

# average usage per room
print(energy.mean(axis=0))

[235 355 172 466 272]
[192 194 209 181 223 255 246]
[33.57142857 50.71428571 24.57142857 66.57142857 38.85714286]


## Finding Patterns Fast

In [12]:
room_totals = energy.sum(axis=0)
day_totals = energy.sum(axis=1)

most_expensive_room = np.argmax(room_totals)
highest_usage_day = np.argmax(day_totals)

print(room_totals)
print(day_totals)
print(most_expensive_room)
print(highest_usage_day)


[235 355 172 466 272]
[192 194 209 181 223 255 246]
3
5


In [13]:

# Find all readings above 50 kWh
high_usage = energy > 50
print(high_usage)

# Extract only those values
print(energy[high_usage])

# Count how many high-usage readings exist
print(np.sum(high_usage))



[[False False False  True False]
 [False False False  True False]
 [False False False  True False]
 [False False False  True False]
 [False  True False  True False]
 [False  True False  True False]
 [False  True False  True False]]
[60 58 65 55 52 70 60 80 58 78]
10


In [14]:
budget = np.array([35, 50, 25, 65, 40])

over_budget = energy > budget
print(over_budget)



[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True  True  True False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [15]:
over_budget = energy > budget

# Count over-budget days per room
print(over_budget.sum(axis=0))

# Count over-budget rooms per day
print(over_budget.sum(axis=1))

# Replace normal values with 0, keep only over-budget readings
flagged = np.where(over_budget, energy, 0)
print(flagged)





[2 3 3 3 2]
[0 0 0 0 3 5 5]
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 52 26 70  0]
 [40 60 30 80 45]
 [38 58 28 78 44]]


In [16]:
room_means = energy.mean(axis=0)
normalized = energy / room_means

print(room_means)
print(normalized.round(2))

[33.57142857 50.71428571 24.57142857 66.57142857 38.85714286]
[[0.89 0.89 0.9  0.9  0.9 ]
 [0.95 0.93 0.85 0.87 0.93]
 [0.92 0.99 1.02 0.98 0.98]
 [0.86 0.85 0.81 0.83 0.88]
 [1.04 1.03 1.06 1.05 1.03]
 [1.19 1.18 1.22 1.2  1.16]
 [1.13 1.14 1.14 1.17 1.13]]


In [17]:
day_totals = energy.sum(axis=1)

mean_total = day_totals.mean()
std_total = day_totals.std()

z_scores = (day_totals - mean_total) / std_total
print(z_scores.round(2))


unusual_days = np.abs(z_scores) > 1.2
print(unusual_days)


[-0.85 -0.78 -0.2  -1.27  0.33  1.56  1.21]
[False False False  True False  True  True]


In [ ]:
import numpy as np

print(energy.mean(axis=1))

room_totals = energy.sum(axis=0)
print(room_totals)

print(np)

[38.4 38.8 41.8 36.2 44.6 51.  49.2]
[235 355 172 466 272]
[235 355 172 466 272]


In [19]:
budget = np.array([35, 50, 25, 65, 40])

over_budget = energy > budget
print(over_budget)

print(over_budget.sum(axis=0))

print(energy[over_budget])

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True  True  True False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[2 3 3 3 2]
[52 26 70 40 60 30 80 45 38 58 28 78 44]


In [20]:
discounted_energy = np.where(energy > 60,energy * 0.9,energy)

print(discounted_energy)

[[30.  45.  22.  60.  35. ]
 [32.  47.  21.  58.  36. ]
 [31.  50.  25.  58.5 38. ]
 [29.  43.  20.  55.  34. ]
 [35.  52.  26.  63.  40. ]
 [40.  60.  30.  72.  45. ]
 [38.  58.  28.  70.2 44. ]]


In [23]:
room_totals = energy.sum(axis=0)
print(room_totals)

room_means = energy.mean(axis=0)
normalized = energy / room_means
print(normalized.mean(axis=0))

[235 355 172 466 272]
[1. 1. 1. 1. 1.]
